const ShopActionTpyes = {
    FETCH_COLLECTIONS_STARTS: 'FETCH_COLLECTIONS_STARTS',
    FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIONS_FAILURE'
}

export default ShopActionTpyes;